function s = mutant_analysis(directory)
root = directory;
cd(root);

tags = {'CDC14', 'CBF5'};
phase = {'G1', 'M'};
rdna_state = {'wt', 'ycg1d2','fob1d'};
metrics = {'otsu_area_array', 'int_int_array', 'log_array', 'rho', 'pval'};
for t_cnt = 1:numel(tags)
    s.(tags{t_cnt}) = struct;
    for p_cnt = 1:numel(phase)
        s.(tags{t_cnt}).(phase{p_cnt}) = struct;
        for r_cnt = 1:numel(rdna_state)
            s.(tags{t_cnt}).(phase{p_cnt}).(rdna_state{r_cnt}) = struct;
            dir_s = dir(sprintf('*_%s_%s-*FP*%s_55x55',...
                rdna_state{r_cnt}, tags{t_cnt}, phase{p_cnt}));
            if numel(dir_s) > 1 || numel(dir_s) == 0
                error('Found multiple or no directory matches');
            end
            [...
                s.(tags{t_cnt}).(phase{p_cnt}).(rdna_state{r_cnt}).(metrics{1}),...
                s.(tags{t_cnt}).(phase{p_cnt}).(rdna_state{r_cnt}).(metrics{2}),...
                s.(tags{t_cnt}).(phase{p_cnt}).(rdna_state{r_cnt}).(metrics{3}),...
                ] = quant_int(dir_s(1).name);
            %% Calculate and add rho and pval
            [...
                s.(tags{t_cnt}).(phase{p_cnt}).(rdna_state{r_cnt}).(metrics{4}),...
                s.(tags{t_cnt}).(phase{p_cnt}).(rdna_state{r_cnt}).(metrics{5}),...
                ] = corr(...
                s.(tags{t_cnt}).(phase{p_cnt}).(rdna_state{r_cnt}).(metrics{1})',...
                (s.(tags{t_cnt}).(phase{p_cnt}).(rdna_state{r_cnt}).(metrics{2})...
                ./s.(tags{t_cnt}).(phase{p_cnt}).(rdna_state{r_cnt}).(metrics{1}))');
        end
    end
end
            