function [g1, m, labels] = parse_barchart_data(S)
%%parse_barchart_data parses structured array to gather mean ans SEM
%%statistics on DMSO and Rapamycin treated cells

labels = { ...
    'Cdc14-GFP DMSO', ...
    'Cdc14-GFP Rapamycin', ...
    'Net1-GFP DMSO', ...
    'Net1-GFP Rapamycin', ...
    'Cbf5-GFP DMSO', ...
    'Cbf5-GFP Rapamycin', ...
    'Nop56-GFP DMSO', ...
    'Nop56-GFP Rapamycin'
    };

g1.mean_vols = [ ...
    nanmean(S.cdc14.dmso.g1.vols), ...
    nanmean(S.cdc14.rap.g1.vols), ...
    nanmean(S.net1.dmso.g1.vols), ...
    nanmean(S.net1.rap.g1.vols), ...
    nanmean(S.cbf5.dmso.g1.vols), ...
    nanmean(S.cbf5.rap.g1.vols), ...
    nanmean(S.nop56.dmso.g1.vols), ...
    nanmean(S.nop56.rap.g1.vols)
    ];

g1.sem_vols = [ ...
    nanstd(S.cdc14.dmso.g1.vols)/sqrt(numel(S.cdc14.dmso.g1.vols)), ...
    nanstd(S.cdc14.rap.g1.vols)/sqrt(numel(S.cdc14.rap.g1.vols)), ...
    nanstd(S.net1.dmso.g1.vols)/sqrt(numel(S.net1.dmso.g1.vols)), ...
    nanstd(S.net1.rap.g1.vols)/sqrt(numel(S.net1.rap.g1.vols)), ...
    nanstd(S.cbf5.dmso.g1.vols)/sqrt(numel(S.cbf5.dmso.g1.vols)), ...
    nanstd(S.cbf5.rap.g1.vols)/sqrt(numel(S.cbf5.rap.g1.vols)), ...
    nanstd(S.nop56.dmso.g1.vols)/sqrt(numel(S.nop56.dmso.g1.vols)), ...
    nanstd(S.nop56.rap.g1.vols)/sqrt(numel(S.nop56.rap.g1.vols))
    ];

m.mean_vols = [ ...
    nanmean(S.cdc14.dmso.m.vols), ...
    nanmean(S.cdc14.rap.m.vols), ...
    nanmean(S.net1.dmso.m.vols), ...
    nanmean(S.net1.rap.m.vols), ...
    nanmean(S.cbf5.dmso.m.vols), ...
    nanmean(S.cbf5.rap.m.vols), ...
    nanmean(S.nop56.dmso.m.vols), ...
    nanmean(S.nop56.rap.m.vols)
    ];

m.sem_vols = [ ...
    nanstd(S.cdc14.dmso.m.vols)/sqrt(numel(S.cdc14.dmso.m.vols)), ...
    nanstd(S.cdc14.rap.m.vols)/sqrt(numel(S.cdc14.rap.m.vols)), ...
    nanstd(S.net1.dmso.m.vols)/sqrt(numel(S.net1.dmso.m.vols)), ...
    nanstd(S.net1.rap.m.vols)/sqrt(numel(S.net1.rap.m.vols)), ...
    nanstd(S.cbf5.dmso.m.vols)/sqrt(numel(S.cbf5.dmso.m.vols)), ...
    nanstd(S.cbf5.rap.m.vols)/sqrt(numel(S.cbf5.rap.m.vols)), ...
    nanstd(S.nop56.dmso.m.vols)/sqrt(numel(S.nop56.dmso.m.vols)), ...
    nanstd(S.nop56.rap.m.vols)/sqrt(numel(S.nop56.rap.m.vols))
    ];

g1.mean_ints = [ ...
    nanmean(S.cdc14.dmso.g1.mean_ints), ...
    nanmean(S.cdc14.rap.g1.mean_ints), ...
    nanmean(S.net1.dmso.g1.mean_ints), ...
    nanmean(S.net1.rap.g1.mean_ints), ...
    nanmean(S.cbf5.dmso.g1.mean_ints), ...
    nanmean(S.cbf5.rap.g1.mean_ints), ...
    nanmean(S.nop56.dmso.g1.mean_ints), ...
    nanmean(S.nop56.rap.g1.mean_ints)
    ];

g1.sem_mean_ints = [ ...
    nanstd(S.cdc14.dmso.g1.mean_ints)/sqrt(numel(S.cdc14.dmso.g1.mean_ints)), ...
    nanstd(S.cdc14.rap.g1.mean_ints)/sqrt(numel(S.cdc14.rap.g1.mean_ints)), ...
    nanstd(S.net1.dmso.g1.mean_ints)/sqrt(numel(S.net1.dmso.g1.mean_ints)), ...
    nanstd(S.net1.rap.g1.mean_ints)/sqrt(numel(S.net1.rap.g1.mean_ints)), ...
    nanstd(S.cbf5.dmso.g1.mean_ints)/sqrt(numel(S.cbf5.dmso.g1.mean_ints)), ...
    nanstd(S.cbf5.rap.g1.mean_ints)/sqrt(numel(S.cbf5.rap.g1.mean_ints)), ...
    nanstd(S.nop56.dmso.g1.mean_ints)/sqrt(numel(S.nop56.dmso.g1.mean_ints)), ...
    nanstd(S.nop56.rap.g1.mean_ints)/sqrt(numel(S.nop56.rap.g1.mean_ints))
    ];

m.mean_ints = [ ...
    nanmean(S.cdc14.dmso.m.mean_ints), ...
    nanmean(S.cdc14.rap.m.mean_ints), ...
    nanmean(S.net1.dmso.m.mean_ints), ...
    nanmean(S.net1.rap.m.mean_ints), ...
    nanmean(S.cbf5.dmso.m.mean_ints), ...
    nanmean(S.cbf5.rap.m.mean_ints), ...
    nanmean(S.nop56.dmso.m.mean_ints), ...
    nanmean(S.nop56.rap.m.mean_ints)
    ];

m.sem_mean_ints = [ ...
    nanstd(S.cdc14.dmso.m.mean_ints)/sqrt(numel(S.cdc14.dmso.m.mean_ints)), ...
    nanstd(S.cdc14.rap.m.mean_ints)/sqrt(numel(S.cdc14.rap.m.mean_ints)), ...
    nanstd(S.net1.dmso.m.mean_ints)/sqrt(numel(S.net1.dmso.m.mean_ints)), ...
    nanstd(S.net1.rap.m.mean_ints)/sqrt(numel(S.net1.rap.m.mean_ints)), ...
    nanstd(S.cbf5.dmso.m.mean_ints)/sqrt(numel(S.cbf5.dmso.m.mean_ints)), ...
    nanstd(S.cbf5.rap.m.mean_ints)/sqrt(numel(S.cbf5.rap.m.mean_ints)), ...
    nanstd(S.nop56.dmso.m.mean_ints)/sqrt(numel(S.nop56.dmso.m.mean_ints)), ...
    nanstd(S.nop56.rap.m.mean_ints)/sqrt(numel(S.nop56.rap.m.mean_ints))
    ];

g1.mean_comps = [ ...
    nanmean(S.cdc14.dmso.g1.comps), ...
    nanmean(S.cdc14.rap.g1.comps), ...
    nanmean(S.net1.dmso.g1.comps), ...
    nanmean(S.net1.rap.g1.comps), ...
    nanmean(S.cbf5.dmso.g1.comps), ...
    nanmean(S.cbf5.rap.g1.comps), ...
    nanmean(S.nop56.dmso.g1.comps), ...
    nanmean(S.nop56.rap.g1.comps)
    ];

g1.sem_comps = [ ...
    nanstd(S.cdc14.dmso.g1.comps)/sqrt(numel(S.cdc14.dmso.g1.comps)), ...
    nanstd(S.cdc14.rap.g1.comps)/sqrt(numel(S.cdc14.rap.g1.comps)), ...
    nanstd(S.net1.dmso.g1.comps)/sqrt(numel(S.net1.dmso.g1.comps)), ...
    nanstd(S.net1.rap.g1.comps)/sqrt(numel(S.net1.rap.g1.comps)), ...
    nanstd(S.cbf5.dmso.g1.comps)/sqrt(numel(S.cbf5.dmso.g1.comps)), ...
    nanstd(S.cbf5.rap.g1.comps)/sqrt(numel(S.cbf5.rap.g1.comps)), ...
    nanstd(S.nop56.dmso.g1.comps)/sqrt(numel(S.nop56.dmso.g1.comps)), ...
    nanstd(S.nop56.rap.g1.comps)/sqrt(numel(S.nop56.rap.g1.comps))
    ];

m.mean_comps = [ ...
    nanmean(S.cdc14.dmso.m.comps), ...
    nanmean(S.cdc14.rap.m.comps), ...
    nanmean(S.net1.dmso.m.comps), ...
    nanmean(S.net1.rap.m.comps), ...
    nanmean(S.cbf5.dmso.m.comps), ...
    nanmean(S.cbf5.rap.m.comps), ...
    nanmean(S.nop56.dmso.m.comps), ...
    nanmean(S.nop56.rap.m.comps)
    ];

m.sem_comps = [ ...
    nanstd(S.cdc14.dmso.m.comps)/sqrt(numel(S.cdc14.dmso.m.comps)), ...
    nanstd(S.cdc14.rap.m.comps)/sqrt(numel(S.cdc14.rap.m.comps)), ...
    nanstd(S.net1.dmso.m.comps)/sqrt(numel(S.net1.dmso.m.comps)), ...
    nanstd(S.net1.rap.m.comps)/sqrt(numel(S.net1.rap.m.comps)), ...
    nanstd(S.cbf5.dmso.m.comps)/sqrt(numel(S.cbf5.dmso.m.comps)), ...
    nanstd(S.cbf5.rap.m.comps)/sqrt(numel(S.cbf5.rap.m.comps)), ...
    nanstd(S.nop56.dmso.m.comps)/sqrt(numel(S.nop56.dmso.m.comps)), ...
    nanstd(S.nop56.rap.m.comps)/sqrt(numel(S.nop56.rap.m.comps))
    ];