%% Cdc14-GFP Cbf5-mCherry file parsing
load Nop56GFP_Net1mCh_dirs.mat;
treatments = {'gal', 'glu'};
phases = {'g1', 'm'};
return_dir = pwd;
for t = 1:numel(treatments)
    for p = 1:numel(phases)
        cd(return_dir);
        cd(S.(treatments{t}).(phases{p}).dir);
        net1_files = dir('*RFP.tif');
        for f = 1:numel(net1_files)
            rdna_filename = net1_files(f).name;
            nuc_filename = strrep(rdna_filename, 'RFP.tif', 'GFP.tif');
            [ ...
                S.(treatments{t}).(phases{p}).rhos(f), ...
                S.(treatments{t}).(phases{p}).rdna_vols(f), ...
                S.(treatments{t}).(phases{p}).rdna_stds(f), ...
                S.(treatments{t}).(phases{p}).nuc_vols(f), ...
                S.(treatments{t}).(phases{p}).nuc_stds(f) ...
                ] = noy_quant(rdna_filename, nuc_filename, 0.0645, 0.2);
        end
        %summarize rhos
        S.(treatments{t}).(phases{p}).mean_rhos = mean( ...
            S.(treatments{t}).(phases{p}).rhos);
        S.(treatments{t}).(phases{p}).sem_rhos = std( ...
            S.(treatments{t}).(phases{p}).rhos)./ ...
            sqrt(numel(S.(treatments{t}).(phases{p}).rhos));
        %summarize rdna vols
        S.(treatments{t}).(phases{p}).mean_rdna_vols = mean( ...
            S.(treatments{t}).(phases{p}).rdna_vols);
        S.(treatments{t}).(phases{p}).sem_rdna_vols = std( ...
            S.(treatments{t}).(phases{p}).rdna_vols)./ ...
            sqrt(numel(S.(treatments{t}).(phases{p}).rdna_vols));
        %sumarize rdna stds
        S.(treatments{t}).(phases{p}).mean_rdna_stds = mean( ...
            S.(treatments{t}).(phases{p}).rdna_stds);
        S.(treatments{t}).(phases{p}).sem_rdna_stds = std( ...
            S.(treatments{t}).(phases{p}).rdna_stds)./ ...
            sqrt(numel(S.(treatments{t}).(phases{p}).rdna_stds));
        %summarize nuc vols
        S.(treatments{t}).(phases{p}).mean_nuc_vols = mean( ...
            S.(treatments{t}).(phases{p}).nuc_vols);
        S.(treatments{t}).(phases{p}).sem_nuc_vols = std( ...
            S.(treatments{t}).(phases{p}).nuc_vols)./ ...
            sqrt(numel(S.(treatments{t}).(phases{p}).nuc_vols));
        %summarize nuc stds
        S.(treatments{t}).(phases{p}).mean_nuc_stds = mean( ...
            S.(treatments{t}).(phases{p}).nuc_stds);
        S.(treatments{t}).(phases{p}).sem_nuc_stds = std( ...
            S.(treatments{t}).(phases{p}).nuc_stds)./ ...
            sqrt(numel(S.(treatments{t}).(phases{p}).nuc_stds));
        
    end
end
%% Nop56-GFP Net1-mCherry bar charts
metrics = {'rhos', 'nuc_vols', 'nuc_stds', 'rdna_vols', 'rdna_stds'};
for m = 1:numel(metrics)
    figure;
    [S.(metrics{m}).c_g1, m_g1] = jgl_anova1({...
        S.gal.g1.(metrics{m}), ...
        S.glu.g1.(metrics{m}) ...
        }, ...
        { ...
        'G1, Tx On', ...
        'G1, Tx Off' ...
        });
    [S.(metrics{m}).c_m, m_m] = jgl_anova1({...
        S.gal.m.(metrics{m}), ...
        S.glu.m.(metrics{m}) ...
        }, ...
        { ...
        'M, Tx On', ...
        'M, Tx Off' ...
        });
    if contains(metrics{m}, 'rdna')
        b = bar([m_g1(:,1); m_m(:,1)], 'LineWidth', 1);
        b.FaceColor = 'flat';
        b.CData = [repmat([178/255, 34/255, 34/255], [2,1]); repmat([128/255, 0, 0], [2,1])];
    elseif contains(metrics{m}, 'nuc')
        b = bar([m_g1(:,1); m_m(:,1)]);
        b.FaceColor = 'flat';
        b.CData = [repmat([154/255, 205/255, 50/255], [2, 1]); repmat([0/255, 128/255, 0/255], [2, 1])];
    else
        b = bar([m_g1(:,1); m_m(:,1)]);
        b.FaceColor = 'flat';
        b.CData = [repmat([0/255, 178/255, 178/255], [2,1]); repmat([0/255, 128/255, 128/255], [2, 1])];
    end
    hold on;
    errorbar([m_g1(:,1); m_m(:,1)], [m_g1(:,2); m_m(:,2)], ...
        'LineStyle', 'none', 'Marker', 'none', 'Color', 'black', 'LineWidth', 1);
    hold off
    xlim([0.5, 4.5]);
    switch m
        case 1
            ylabel({'Net1-mCherry:Nop56-GFP','Correlation'});
        case 2
            ylabel('Nop56-GFP Volume (\mum^3');
        case 3
            ylabel('Rescaled Nop56-GFP Signal STD');
        case 4
            ylabel('Net1-mCherry Volume (\mum^3)');
        case 5
            ylabel('Rescaled Net1-mCherry Signal STD (\mum^3)');
    end
    xticklabels(...
        {'G1, pNOY TX On', 'G1, pNOY TX Off', ...
        'G2/M, pNOY TX On', 'G2/M, pNOY TX Off'});
    set(gcf, 'Units', 'inches');
    set(gcf, 'Position', [5,5,3.25, 2.5]);
    set(gca, 'XTickLabelRotation', 25);
    set(gca, 'LineWidth', 1);
    set(gca, 'FontSize', 12);
    InSet = get(gca, 'TightInset');
    set(gca, 'Position', [InSet(1:2), 1-InSet(1)-InSet(3), 1-InSet(2)-InSet(4)])
    
end

